name: "Static Analysis by PHPStan"

on:
  pull_request:
  push:

jobs:
  static-analysis-psalm:
    name: "Static Analysis by PHPStan"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "phpstan LargeMemoryConsumption"
        run: "../vendor/bin/phpstan analyse --debug -vvv src/LargeMemoryConsumption.php"

      - name: "phpstan MemoryConsumptionMini"
        run: "./vendor/bin/phpstan analyse --debug -vvv src/MemoryConsumptionMini.php"
