name: "Static Analysis by PHPStan"

on:
  pull_request:
  push:

jobs:
  static-analysis-psalm:
    name: "Static Analysis by PHPStan"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v1"
        with:
          php-version: "7.4"
          coverage: none
          ini-values: memory_limit=-1
          tools: composer:v2
          extensions: :amqp :apcu :bcmath :bz2 :curl :dba :enchant :gd :gmp :igbinary :imap :ldap :memcache :memcached :mongodb :msgpack :odbc :pdo_dblib :PDO_Firebird :PDO_ODBC :pdo_pgsql :pdo_sqlite :pgsql :pspell :redis :snmp :soap :sqlite3 :tidy :xmlrpc :yaml :zip :zmq

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "show php module"
        run: "php -m"

      - name: "phpstan LargeMemoryConsumption"
        run: "./vendor/bin/phpstan analyse --debug -vvv src/LargeMemoryConsumption.php"

      - name: "phpstan MemoryConsumptionMini"
        run: "./vendor/bin/phpstan analyse --debug -vvv src/MemoryConsumptionMini.php"
